AllCops:
  Exclude:
    - 'scripts/benchmark.rb'
    - 'vendor/**/*' # need for travis-ci
    # http://caseywest.com/faster-ci-on-travis-and-docker-for-ruby-and-rails-and-rubocop/ 

Style/EndOfLine:
  Enabled: false

Metrics/MethodLength:
  Max: 25

Style/BlockComments:
  Enabled: false

Metrics/AbcSize:
  Max: 25

Style/RescueModifier:
  Enabled: false

Metrics/ClassLength:
   Max: 120
